apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch-connector-1
  labels:
    app: elasticsearch-connector
spec:
  affinity:
    # Try to avoid scheduling the pods on the same node
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - elasticsearch-connector
          topologyKey: failure-domain.beta.kubernetes.io/zone
  containers:
  - image: registry/image:tag # Replace with your image
    imagePullPolicy: IfNotPresent
    name: connector
    resources:
      limits:
        cpu: '8'
        memory: '16Gi'
      requests:
        cpu: '4'
        memory: '8Gi'
    env:
      - name: CBES_MEMBERNUMBER
        value: "1" # Number of *this* pod from the total set
      - name: CBES_TOTALMEMBERS
        value: "2" # Number of pods being deployed
    volumeMounts:
    - mountPath: /opt/couchbase-elasticsearch-connector/config
      name: config
      readOnly: true
    - mountPath: /opt/couchbase-elasticsearch-connector/secrets
      name: secrets
      readOnly: true
  restartPolicy: Always
  volumes:
  - name: config
    configMap:
      name: elasticsearch-connector-configuration
  - name: secrets
    secret:
      secretName: elasticsearch-connector-secrets
---
apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch-connector-2
  labels:
    app: elasticsearch-connector
spec:
  affinity:
    # Try to avoid scheduling the pods on the same node
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - elasticsearch-connector
          topologyKey: failure-domain.beta.kubernetes.io/zone
  containers:
  - image: registry/image:tag # Replace with your image
    imagePullPolicy: IfNotPresent
    name: connector
    resources:
      limits:
        cpu: '8'
        memory: '16Gi'
      requests:
        cpu: '4'
        memory: '8Gi'
    env:
      - name: CBES_MEMBERNUMBER
        value: "2" # Number of *this* pod from the total set
      - name: CBES_TOTALMEMBERS
        value: "2" # Number of pods being deployed
    volumeMounts:
    - mountPath: /opt/couchbase-elasticsearch-connector/config
      name: config
      readOnly: true
    - mountPath: /opt/couchbase-elasticsearch-connector/secrets
      name: secrets
      readOnly: true
  restartPolicy: Always
  volumes:
  - name: config
    configMap:
      name: elasticsearch-connector-configuration
  - name: secrets
    secret:
      secretName: elasticsearch-connector-secrets